### PR TITLE
adding push protocol

### PR DESCRIPTION
**Pull request by username23456y543**
{
        "dappName": "Push Protocol",
        "dAppWebsite": "https://push.org/",
        "twitterHandle": "https://twitter.com/pushprotocol",
        "supportEIP1271": "Yes",
        "favIcon": "pushprotocol.png"
    }

### CODE REVIEW

**Comment by arddluma** [comment]
Could you please add the logo here in the same PR instead of opening 2? 
I've closed the old one. 
Thanks!

**Comment by arddluma** [comment]
Also, how did you test the EIP1271 support, and with which wallet ?

**Comment by username23456y543** [comment]
@arddluma 

sure, i've committed here https://github.com/username23456y543/eip1271-website/commit/d6458f2912ac2790c31fbecac8d3789a89995e72

For EIP1271 support on push protocol, please refer to point 6 in their official blog post
"6) Including of EIP-1271 in the Push Communicator contract"
https://medium.com/push-protocol/introducing-push-protocol-v1-5-80eb39b55424

**Comment by arddluma** [comment]
> @arddluma
> 
> sure, i've committed here [username23456y543@d6458f2](https://github.com/username23456y543/eip1271-website/commit/d6458f2912ac2790c31fbecac8d3789a89995e72)
> 
> For EIP1271 support on push protocol, please refer to point 6 in their official blog post "6) Including of EIP-1271 in the Push Communicator contract" https://medium.com/push-protocol/introducing-push-protocol-v1-5-80eb39b55424

Appreciate your contribution! Thank you. Merging

**Pull request merged**
